In [225]:
from bs4 import BeautifulSoup
import requests
import csv
import datetime
import re
import pandas as pd
import numpy as np
import csv

In [4]:
(Team_1, Team_2, Winner, Margin, Ground, Ground_url, Match_Date, Scorecard, Scorecard_url) = ([],[],[],[],[],[],[],[],[])

now =datetime.datetime.now()
max_Year = now.year


for year in range(1971,max_Year+1):
    # Collect first page of list
    url = 'http://stats.espncricinfo.com/ci/engine/records/team/match_results.html?class=2;id='+str(year)+';type=year'
    page = requests.get(url)
    # Create a BeautifulSoup object
    soup = BeautifulSoup(page.text, 'lxml')
    Match_Result_Year_Table = soup.find('table', class_ = 'engineTable')
    year_Records = Match_Result_Year_Table.find_all('tbody')
    year_Records =BeautifulSoup(str(year_Records), 'lxml')
    for i in range(len(year_Records.find_all('tr'))):
        # print(i , year)
        record =year_Records.find_all('tr')[i]
        td_records = record.find_all('td')
        Team_1.append((td_records[0].text))
        Team_2.append((td_records[1].text))
        Winner.append((td_records[2].text))
        Margin.append((td_records[3].text))
        Ground.append((td_records[4].string))
        Ground_url.append((str(td_records[4]).split(".")[0].split("/")[-1]))
        Match_Date.append((td_records[5].text))
        Scorecard.append((td_records[6].text))
        Scorecard_url.append((str(td_records[6]).split(".")[0].split("/")[-1]))



In [5]:
import pandas as pd
ONE_DAY_INTERNATIONALS = pd.DataFrame()
ONE_DAY_INTERNATIONALS['Team_1'] = Team_1
ONE_DAY_INTERNATIONALS['Team_2'] = Team_2
ONE_DAY_INTERNATIONALS['Winner'] = Winner
ONE_DAY_INTERNATIONALS['Margin'] = Margin
ONE_DAY_INTERNATIONALS['Ground'] = Ground
ONE_DAY_INTERNATIONALS['Ground_url'] = Ground_url
ONE_DAY_INTERNATIONALS['Match_Date'] = Match_Date
ONE_DAY_INTERNATIONALS['Scorecard'] = Scorecard
ONE_DAY_INTERNATIONALS['Scorecard_url'] = Scorecard_url
ONE_DAY_INTERNATIONALS.count()
# ONE_DAY_INTERNATIONALS.Ground_url.unique()


Team_1           4179
Team_2           4179
Winner           4179
Margin           4179
Ground           4179
Ground_url       4179
Match_Date       4179
Scorecard        4179
Scorecard_url    4179
dtype: int64

In [237]:
ONE_DAY_INTERNATIONALS = pd.read_csv('ONE_DAY_INTERNATIONALS.csv')
ONE_DAY_INTERNATIONALS.head()

Team_1     Team_2       Winner     Margin        Ground  Ground_url  \
0    Australia    England    Australia  5 wickets     Melbourne       56441   
1      England  Australia      England  6 wickets    Manchester       57160   
2      England  Australia    Australia  5 wickets        Lord's       57129   
3      England  Australia      England  2 wickets    Birmingham       56788   
4  New Zealand   Pakistan  New Zealand    22 runs  Christchurch       58812   

  Match_Date Scorecard  Scorecard_url  
0   5-Jan-71   ODI # 1          64148  
1  24-Aug-72   ODI # 2          64944  
2  26-Aug-72   ODI # 3          64945  
3  28-Aug-72   ODI # 4          64946  
4  11-Feb-73   ODI # 5          64149

In [271]:
ground_list = ONE_DAY_INTERNATIONALS.Ground_url.unique()
ground_list.sort()
ground_list[1:50]

array([56319, 56322, 56326, 56336, 56362, 56370, 56390, 56397, 56407,
       56410, 56420, 56430, 56441, 56450, 56490, 56544, 56656, 56658,
       56661, 56667, 56670, 56689, 56691, 56708, 56717, 56788, 56825,
       56831, 56869, 56874, 56887, 56901, 56953, 57092, 57100, 57127,
       57129, 57160, 57207, 57219, 57290, 57309, 57312, 57347, 57351,
       57367, 57424, 57851, 57852], dtype=int64)

In [272]:
ground_list[50:100]

array([57871, 57897, 57980, 57991, 57993, 58008, 58027, 58040, 58044,
       58056, 58081, 58114, 58119, 58136, 58142, 58150, 58151, 58162,
       58164, 58180, 58187, 58204, 58230, 58273, 58301, 58317, 58324,
       58344, 58373, 58383, 58401, 58456, 58479, 58516, 58519, 58537,
       58542, 58547, 58588, 58604, 58607, 58652, 58655, 58657, 58658,
       58659, 58661, 58678, 58686, 58693], dtype=int64)

In [273]:
ground_list[100:150]

array([58718, 58728, 58792, 58810, 58812, 58822, 58827, 58831, 58847,
       58857, 58865, 58879, 58895, 58899, 58919, 58927, 58930, 58936,
       58956, 58967, 58982, 58986, 58988, 58995, 58996, 59004, 59006,
       59011, 59014, 59016, 59018, 59039, 59042, 59068, 59079, 59089,
       59098, 59120, 59135, 59147, 59151, 59159, 59172, 59255, 59258,
       59269, 59275, 59303, 59306, 59308], dtype=int64)

In [274]:
ground_list[150:230]

array([  59325,   59329,   59350,   59368,   59387,   59389,   59392,
         59396,   59417,   59421,   59429,   59434,   59447,   59458,
         59463,   59475,   59480,   59490,   59492,   59495,   59518,
         59534,   59537,   59545,   59547,   59560,   59590,  208543,
        208544,  236761,  256592,  271573,  298311,  304364,  375326,
        377285,  392627,  424917,  434210,  434211,  441704,  444258,
        461400,  475201,  481147,  485865,  493864,  518990,  545380,
        680295,  942501, 1120086, 1126475, 1145946], dtype=int64)

In [15]:
ground_list[200:300]

array([ 942501, 1120086, 1126475, 1145946], dtype=int64)

In [269]:
url = 'http://stats.espncricinfo.com/ci/engine/ground/56319.html?class=2;template=results;type=aggregate'
page = requests.get(url) 
soup = BeautifulSoup(page.text, 'lxml')    
headlinks = soup.find_all('table')[3]
headlinks = headlinks.find_all('tr', class_="headlinks")
headlinks = BeautifulSoup(str(headlinks), 'lxml')
# print(headlinks.find_all('th'))
len_headlinks = len(headlinks.find_all('th'))
len_headlinks



13

In [276]:
record_series = pd.DataFrame()
record_ground = pd.DataFrame()
record_series_spam= pd.DataFrame()
record_ground_spam= pd.DataFrame()
for ground_number in ground_list:
    # Collect first page of list
    url = 'http://stats.espncricinfo.com/ci/engine/ground/'+str(ground_number)+'.html?class=2;template=results;type=aggregate'
    # print(ground_number)
    # url = 'http://stats.espncricinfo.com/ci/engine/ground/56319.html?class=2;template=results;type=aggregate'
    page = requests.get(url) 
    soup = BeautifulSoup(page.text, 'lxml')    
    headlinks = soup.find_all('table')[3]
    # print(headlinks)
    headlinks = headlinks.find_all('tr', class_="headlinks")
    headlinks = BeautifulSoup(str(headlinks), 'lxml')
    # print(headlinks.find_all('th'))
    len_headlinks = len(headlinks.find_all('th'))
    # print(len_headlinks)
    if len_headlinks == 14:
        column_list = ['Ground_overall','playing_span','matches_played','matches_won','matches_lost','matches_tied','matches_with_no_result' ,'win_loss_ratio','runs_scored','wickets_taken','balls_bowled','average_runs_per_wicket','average_runs_per_six_balls','profile', 'ground_url']
        records_tag = soup.find_all('tr', class_ ='data1')
        records_tag = list(records_tag)
        # print(records_tag)
        for tr_tag in range(len(records_tag)):
            # print(tr_tag)
            new_records_tag =BeautifulSoup(str(records_tag[tr_tag]), 'lxml')
            # print(new_records_tag)
            new_td_records_tag = new_records_tag.find_all('td')
            # print(new_td_records_tag)
            record_list_spam = []
            for record_tag in new_td_records_tag:
                record_list_spam.append(record_tag.text.strip())
            # print(record_list_spam)
            record_list_spam.append(ground_number)
            record_ground_spam.append(record_list_spam)
            with open('record_ground_spam0.csv', 'a') as csvFile:
                writer = csv.writer(csvFile)
                writer.writerow(record_list_spam)
            csvFile.close()
    else:
        column_list = ['Ground_overall','matches_played','matches_won','matches_lost','matches_tied','matches_with_no_result' ,'win_loss_ratio','runs_scored','wickets_taken','balls_bowled','average_runs_per_wicket','average_runs_per_six_balls','profile', 'ground_url']
        records_tag = soup.find_all('tr', class_ ='data1')
        records_tag = list(records_tag)
        # print(records_tag)
        for tr_tag in range(len(records_tag)):
            # print(tr_tag)
            new_records_tag =BeautifulSoup(str(records_tag[tr_tag]), 'lxml')
            # print(new_records_tag)
            new_td_records_tag = new_records_tag.find_all('td')
            # print(new_td_records_tag)
            record_list = []
            for record_tag in new_td_records_tag:
                record_list.append(record_tag.text.strip())
            # print(record_list)
            record_list.append(ground_number)
            record_ground.append(record_list)
            with open('record_ground0.csv', 'a') as csvFile:
                writer = csv.writer(csvFile)
                writer.writerow(record_list)
            csvFile.close()



In [281]:
column_list_spam =  ['Ground_overall','playing_span','matches_played','matches_won','matches_lost','matches_tied','matches_with_no_result' ,'win_loss_ratio','runs_scored','wickets_taken','balls_bowled','average_runs_per_wicket','average_runs_per_six_balls','profile', 'ground_url']
record_ground_spam= pd.read_csv("record_ground_spam.csv", names=column_list_spam )
column_lists =  ['Ground_overall','matches_played','matches_won','matches_lost','matches_tied','matches_with_no_result' ,'win_loss_ratio','runs_scored','wickets_taken','balls_bowled','average_runs_per_wicket','average_runs_per_six_balls','profile', 'ground_url']
record_ground = pd.read_csv("record_ground.csv", names=column_lists )

In [282]:
record_ground_spam.head()

Ground_overall playing_span  matches_played  matches_won  matches_lost  \
0        overall    1975-2019            85.0         83.0          83.0   
1      Australia    1975-2019            52.0         36.0          16.0   
2     Bangladesh    2015-2015             1.0          1.0           0.0   
3        England    1980-2018            17.0          4.0          12.0   
4          India    1980-2019            15.0          9.0           5.0   

   matches_tied  matches_with_no_result win_loss_ratio  runs_scored  \
0           1.0                     1.0          1.000      36735.0   
1           0.0                     0.0          2.250      11466.0   
2           0.0                     0.0              -        275.0   
3           0.0                     1.0          0.333       3476.0   
4           1.0                     0.0          1.800       3450.0   

   wickets_taken  balls_bowled average_runs_per_wicket  \
0         1244.0       47123.0                   29.52   
1          339.0       14217.0                   33.82   
2            7.0         300.0                   39.28   
3          135.0        4490.0                   25.74   
4          109.0        4239.0                   31.65   

  average_runs_per_six_balls  profile  ground_url  
0                       4.67  Profile     56293.0  
1                       4.83      NaN     56293.0  
2                       5.50      NaN     56293.0  
3                       4.64      NaN     56293.0  
4                       4.88      NaN     56293.0

In [283]:
record_ground.head()

Ground_overall  matches_played  matches_won  matches_lost  matches_tied  \
0        overall               1          1.0           1.0           0.0   
1        England               1          0.0           1.0           0.0   
2       Zimbabwe               1          1.0           0.0           0.0   
3            NaN           56319          NaN           NaN           NaN   
4        neutral               1          1.0           1.0           0.0   

   matches_with_no_result win_loss_ratio  runs_scored  wickets_taken  \
0                     0.0          1.000        259.0           20.0   
1                     0.0          0.000        125.0           10.0   
2                     0.0              -        134.0           10.0   
3                     NaN            NaN          NaN            NaN   
4                     0.0          1.000        259.0           20.0   

   balls_bowled average_runs_per_wicket average_runs_per_six_balls  profile  \
0         572.0                   12.95                       2.71  Profile   
1         295.0                   12.50                       2.54      NaN   
2         277.0                   13.40                       2.90      NaN   
3           NaN                     NaN                        NaN      NaN   
4         572.0                   12.95                       2.71      NaN   

   ground_url  
0     56319.0  
1     56319.0  
2     56319.0  
3         NaN  
4     56319.0

In [ ]:
# Ground details 

column_list = ['Ground_overall','playing_span','matches_played','matches_won','matches_lost','matches_tied','matches_with_no_result' ,'win_loss_ratio','runs_scored','wickets_taken','balls_bowled','average_runs_per_wicket','average_runs_per_six_balls','profile', 'ground_url']
Ground_Details_Temp = pd.DataFrame()
Ground_Details = pd.DataFrame()
for ground_number in ground_list:
    # Collect first page of list
    #url = 'http://stats.espncricinfo.com/ci/engine/records/team/match_results.html?class=2;id='+str(year)+';type=year'
    # page = requests.get(url)    
    url = 'http://stats.espncricinfo.com/ci/engine/ground/'+str(ground_number)+'.html?class=2;template=results;type=aggregate'
    page = requests.get(url)
    #print(ground_number)
    soup = BeautifulSoup(page.text, 'lxml')
    #print(soup.prettify())
    result = soup.find_all('table')
    # print(len(result), ground_number)
    result = soup.find_all('table')[2]
    records_tag = result.find_all('tr', class_ ='data1')
    records_tag =BeautifulSoup(str(records_tag), 'lxml')
    records_tag = records_tag.find_all('td')
    record_list = []
    for record_tag in records_tag:
        record_list.append(record_tag.text.strip())
    record_list.append(ground_number.strip())
    Ground_Details_Temp =Ground_Details_Temp.append(pd.Series([record_list]),ignore_index=True)
    Ground_Details= Ground_Details.append(Ground_Details_Temp[0].tolist())
Ground_Details.columns = [column_list]
pd.DataFrame(Ground_Details)
Ground_Details.to_csv('Ground_Details.csv')